Change to using name to identify port

diff --git a/pianomarvel_midi_shortcuts b/pianomarvel_midi_shortcuts
--- a/pianomarvel_midi_shortcuts
+++ b/pianomarvel_midi_shortcuts
@@ -9,8 +9,7 @@ NOTE_NEXT_SONG="UNSET"
 NOTE_PREV_SONG="UNSET"
 NOTE_EXIT_SCREEN='UNSET'
 
-
-# Do not modify below ( unless of course you really want to :) )
+# Do not modify below (unless of course you really want to :)
 KEY_START_PRACTICE='1'
 KEY_START_ASSESSMENT='2'
 KEY_REPEAT_LAST_MODE='space'
@@ -20,17 +19,34 @@ KEY_NEXT_SONG="Right"
 KEY_PREV_SONG="Left"
 KEY_EXIT_SCREEN='Esc'
 
-aseqdump -p "$1" | \
+
+# Find the ALSA MIDI port whose name matches $1
+PORT=$(aseqdump -l | awk -v name="$1" '
+    index($0, name) {
+        print $1
+        exit
+    }
+')
+
+if [[ -z "$PORT" ]]; then
+    echo "Error: MIDI device '$1' not found." >&2
+    echo "Available MIDI ports:" >&2
+    aseqdump -l >&2
+    exit 1
+fi
+
+echo "Using MIDI device '$1' on port $PORT" >&2
+
+aseqdump -p "$PORT" | \
 while IFS=" ," read src ev1 ev2 ch label1 data1 label2 data2 rest; do
     case "$ev1 $ev2 $data1" in
-        "Note on ${NOTE_START_PRACTICE}" ) xdotool key ${KEY_START_PRACTICE} ;;
-        "Note on ${NOTE_START_ASSESSMENT}" ) xdotool key ${KEY_START_ASSESSMENT} ;;
-        "Note on ${NOTE_REPEAT_LAST_MODE}" ) xdotool key ${KEY_REPEAT_LAST_MODE} ;;
-        "Note on ${NOTE_INCREASE_TEMPO}" ) xdotool key ${KEY_INCREASE_TEMPO} ;;
-        "Note on ${NOTE_DECREASE_TEMPO}" ) xdotool key ${KEY_DECREASE_TEMPO} ;;
-        "Note on ${NOTE_NEXT_SONG}" ) xdotool key ${KEY_NEXT_SONG} ;;
-        "Note on ${NOTE_PREV_SONG}" ) xdotool key ${KEY_PREV_SONG} ;;
-        "Note on ${NOTE_EXIT_SCREEN}" ) xdotool key ${KEY_EXIT_SCREEN} ;;
+        "Note on ${NOTE_START_PRACTICE}" ) xdotool key "${KEY_START_PRACTICE}" ;;
+        "Note on ${NOTE_START_ASSESSMENT}" ) xdotool key "${KEY_START_ASSESSMENT}" ;;
+        "Note on ${NOTE_REPEAT_LAST_MODE}" ) xdotool key "${KEY_REPEAT_LAST_MODE}" ;;
+        "Note on ${NOTE_INCREASE_TEMPO}" ) xdotool key "${KEY_INCREASE_TEMPO}" ;;
+        "Note on ${NOTE_DECREASE_TEMPO}" ) xdotool key "${KEY_DECREASE_TEMPO}" ;;
+        "Note on ${NOTE_NEXT_SONG}" ) xdotool key "${KEY_NEXT_SONG}" ;;
+        "Note on ${NOTE_PREV_SONG}" ) xdotool key "${KEY_PREV_SONG}" ;;
+        "Note on ${NOTE_EXIT_SCREEN}" ) xdotool key "${KEY_EXIT_SCREEN}" ;;
     esac
 done
-
